export const DOMstrings = {
    inputType: '.add__type',
    inputDescription: '.add__description',
    inputValue: '.add__value',
    inputBtn: '.add__btn',
    incomeContainer: '.income__list',
    expenseContainer: '.expenses__list',
    savingsContainer: '.savings__list',
    budgetLabel: '.budget__value',
    incomeLabel: '.budget__income--value',
    expenseLabel: '.budget__expenses--value',
    savingsLabel: '.budget__savings--value',
    incomePercentLabel: '.budget__income--percentage',
    expensePercentLabel: '.budget__expenses--percentage',
    savingsPercentLabel: '.budget__savings--percentage',
    container: '.container',
    expensesPercentageLabel: '.expenses__item__percentage',
    savingsPercentageLabel: '.savings__item__percentage',
    dateLabel: '.budget__title--month'
};
